"""Settings schema for Web UI forms."""

from typing import Any

SETTING_GROUPS: list[dict[str, Any]] = [
    {
        "id": "llm",
        "title": "大语言模型 (LLM)",
        "description": "用于 contextual / proposition 分块及可选 Judge",
        "fields": [
            {"key": "chunk_llm_provider", "label": "提供商", "type": "select", "options": [
                {"value": "deepseek", "label": "DeepSeek"},
                {"value": "openai", "label": "OpenAI"},
                {"value": "mistral", "label": "Mistral"},
                {"value": "anthropic", "label": "Anthropic"},
                {"value": "openai_compatible", "label": "其他（OpenAI 兼容）"},
            ]},
            {"key": "chunk_llm_model", "label": "模型", "type": "text", "placeholder": "deepseek-chat"},
            {"key": "chunk_llm_api_base", "label": "API Base（可选）", "type": "text", "placeholder": "https://api.deepseek.com"},
            {"key": "chunk_llm_api_key", "label": "API Key", "type": "secret", "placeholder": "留空则使用环境变量"},
            {"key": "chunk_llm_temperature", "label": "Temperature", "type": "number", "min": 0, "max": 2, "step": 0.1},
            {"key": "chunk_llm_max_tokens", "label": "Max Tokens", "type": "number", "min": 256, "max": 128000},
        ],
    },
    {
        "id": "vision",
        "title": "视觉模型",
        "description": "解析实验 vlm_pdf：按页 OCR 为 Markdown（多模态 API）",
        "fields": [
            {"key": "parse_vlm_provider", "label": "提供商", "type": "select", "options": [
                {"value": "openai", "label": "OpenAI"},
                {"value": "deepseek", "label": "DeepSeek"},
                {"value": "anthropic", "label": "Anthropic"},
                {"value": "qwen", "label": "通义千问 / DashScope"},
                {"value": "dashscope", "label": "DashScope"},
                {"value": "google_genai", "label": "Google AI"},
                {"value": "mistral", "label": "Mistral"},
                {"value": "openai_compatible", "label": "其他（OpenAI 兼容）"},
            ]},
            {"key": "parse_vlm_model", "label": "视觉模型", "type": "text", "placeholder": "gpt-4o / qwen-vl-max"},
            {"key": "parse_vlm_api_base", "label": "API Base（可选）", "type": "text"},
            {"key": "parse_vlm_api_key", "label": "API Key", "type": "secret", "placeholder": "留空则使用环境变量"},
            {"key": "parse_vlm_max_pages", "label": "单文件最多页数", "type": "number", "min": 0, "max": 500,
             "placeholder": "0=全部页，默认 50"},
            {"key": "parse_vlm_max_workers", "label": "并发页数", "type": "number", "min": 1, "max": 8},
            {"key": "parse_vlm_temperature", "label": "Temperature", "type": "number", "min": 0, "max": 2, "step": 0.1},
            {"key": "parse_vlm_max_tokens", "label": "每页 Max Tokens", "type": "number", "min": 256, "max": 16384},
            {"key": "parse_vlm_dpi", "label": "渲染 DPI", "type": "number", "min": 72, "max": 300},
            {"key": "parse_vlm_max_edge", "label": "图像长边上限 (px)", "type": "number", "min": 512, "max": 2048},
        ],
    },
    {
        "id": "ocr",
        "title": "OCR API",
        "description": "供解析实验「ocr_api」使用；本地 OCR 请直接勾选解析器 ocr_local",
        "fields": [
            {"key": "parse_ocr_api_provider", "label": "OCR 服务商", "type": "select", "options": [
                {"value": "azure", "label": "Microsoft Azure AI Vision"},
                {"value": "baidu", "label": "百度智能云 OCR"},
                {"value": "tencent", "label": "腾讯云 OCR"},
                {"value": "alibaba", "label": "阿里云（DashScope 多模态）"},
                {"value": "dashscope", "label": "DashScope 多模态 OCR"},
                {"value": "qwen", "label": "通义千问多模态 OCR"},
                {"value": "openai", "label": "OpenAI Vision OCR"},
                {"value": "google", "label": "Google Cloud Vision（多模态）"},
                {"value": "huawei", "label": "华为云 OCR（预留）"},
                {"value": "openai_compatible", "label": "OpenAI 兼容接口"},
            ]},
            {"key": "parse_ocr_api_key", "label": "API Key / SecretId", "type": "secret",
             "placeholder": "Azure Key；百度 API Key；腾讯 SecretId"},
            {"key": "parse_ocr_api_secret", "label": "Secret Key（百度/腾讯必填）", "type": "secret",
             "placeholder": "百度 Secret Key；腾讯云 SecretKey"},
            {"key": "parse_ocr_api_base", "label": "API Base / 终结点", "type": "text",
             "placeholder": "Azure: xxx.cognitiveservices.azure.com"},
            {"key": "parse_ocr_api_region", "label": "区域 Region", "type": "text",
             "placeholder": "腾讯云默认 ap-guangzhou",
             "showWhen": {"parse_ocr_api_provider": "tencent"}},
            {"key": "parse_ocr_api_model", "label": "模型 ID", "type": "text",
             "placeholder": "多模态服务商必填，如 gpt-4o / qwen-vl-max"},
            {"key": "parse_ocr_max_pages", "label": "PDF 最多页数（OCR 共用）", "type": "number", "min": 0, "max": 500,
             "placeholder": "0=全部页"},
            {"key": "parse_ocr_dpi", "label": "PDF 渲染 DPI（OCR 共用）", "type": "number", "min": 72, "max": 400},
        ],
    },
    {
        "id": "embedding",
        "title": "嵌入模型 (Embedding)",
        "description": "语义分块与向量检索评测",
        "fields": [
            {"key": "chunk_embedding_provider", "label": "提供商", "type": "select", "options": [
                {"value": "huggingface", "label": "HuggingFace（本地）"},
                {"value": "mistral", "label": "Mistral"},
                {"value": "qwen", "label": "通义千问 / DashScope"},
                {"value": "dashscope", "label": "DashScope"},
                {"value": "deepseek", "label": "DeepSeek"},
                {"value": "openai", "label": "OpenAI"},
                {"value": "openai_compatible", "label": "其他（OpenAI 兼容）"},
            ]},
            {"key": "chunk_embedding_model", "label": "模型名", "type": "text",
             "placeholder": "BAAI/bge-small-zh-v1.5 / mistral-embed / text-embedding-v3"},
            {"key": "chunk_embedding_api_base", "label": "API Base（可选）", "type": "text"},
            {"key": "chunk_embedding_api_key", "label": "API Key", "type": "secret"},
            {"key": "embedding_device", "label": "设备 (HF)", "type": "select", "options": [
                {"value": "cpu", "label": "CPU"},
                {"value": "cuda", "label": "CUDA"},
            ]},
        ],
    },
    {
        "id": "vectorstore",
        "title": "向量库 (Vector Store)",
        "description": "默认内存 FAISS；可切换 Qdrant / Milvus / Chroma / Pinecone",
        "fields": [
            {"key": "vector_store_provider", "label": "提供商", "type": "select", "options": [
                {"value": "faiss", "label": "FAISS（内存，默认）"},
                {"value": "qdrant", "label": "Qdrant"},
                {"value": "milvus", "label": "Milvus"},
                {"value": "chroma", "label": "Chroma"},
                {"value": "pinecone", "label": "Pinecone"},
            ]},
            {"key": "vector_store_collection_prefix", "label": "Collection 前缀", "type": "text"},
            {"key": "qdrant_url", "label": "Qdrant URL", "type": "text", "showWhen": {"vector_store_provider": "qdrant"}},
            {"key": "qdrant_api_key", "label": "Qdrant API Key", "type": "secret", "showWhen": {"vector_store_provider": "qdrant"}},
            {"key": "milvus_uri", "label": "Milvus URI", "type": "text", "showWhen": {"vector_store_provider": "milvus"}},
            {"key": "milvus_token", "label": "Milvus Token", "type": "secret", "showWhen": {"vector_store_provider": "milvus"}},
            {"key": "chroma_persist_dir", "label": "Chroma 持久化目录", "type": "text",
             "placeholder": "留空=内存", "showWhen": {"vector_store_provider": "chroma"}},
            {"key": "pinecone_index_name", "label": "Pinecone Index", "type": "text", "showWhen": {"vector_store_provider": "pinecone"}},
            {"key": "pinecone_api_key", "label": "Pinecone API Key", "type": "secret", "showWhen": {"vector_store_provider": "pinecone"}},
            {"key": "pinecone_namespace", "label": "Namespace", "type": "text", "showWhen": {"vector_store_provider": "pinecone"}},
        ],
    },
    {
        "id": "observability",
        "title": "可观测性",
        "description": "LangSmith / Langfuse，默认关闭",
        "fields": [
            {"key": "langsmith_enabled", "label": "启用 LangSmith", "type": "boolean"},
            {"key": "langsmith_project", "label": "LangSmith Project", "type": "text"},
            {"key": "langsmith_api_key", "label": "LangSmith API Key", "type": "secret"},
            {"key": "langsmith_endpoint", "label": "LangSmith Endpoint", "type": "text"},
            {"key": "langfuse_enabled", "label": "启用 Langfuse", "type": "boolean"},
            {"key": "langfuse_project", "label": "Langfuse Project", "type": "text"},
            {"key": "langfuse_host", "label": "Langfuse Host", "type": "text"},
            {"key": "langfuse_public_key", "label": "Langfuse Public Key", "type": "secret"},
            {"key": "langfuse_secret_key", "label": "Langfuse Secret Key", "type": "secret"},
        ],
    },
    {
        "id": "chunk",
        "title": "分块参数",
        "description": "各策略的默认切分尺寸",
        "fields": [
            {"key": "baseline_chunk_size", "label": "基线 Chunk Size", "type": "number"},
            {"key": "baseline_chunk_overlap", "label": "基线 Overlap", "type": "number"},
            {"key": "semantic_min_chunk_size", "label": "语义最小 Chunk", "type": "number"},
            {"key": "child_chunk_size", "label": "子块 Size", "type": "number"},
            {"key": "parent_chunk_size", "label": "父块 Size", "type": "number"},
            {"key": "contextual_max_chunks", "label": "Contextual 最大块数", "type": "number"},
        ],
    },
    {
        "id": "eval",
        "title": "评测",
        "description": "检索评测与 LLM-as-Judge",
        "fields": [
            {"key": "eval_top_k", "label": "Top-K", "type": "number", "min": 1, "max": 50},
            {"key": "eval_judge_enabled", "label": "启用 LLM-as-Judge", "type": "boolean"},
            {"key": "eval_judge_mode", "label": "Judge 模式", "type": "select", "options": [
                {"value": "both", "label": "子串 + Judge"},
                {"value": "judge", "label": "仅 Judge"},
                {"value": "substring", "label": "仅子串"},
            ]},
            {"key": "eval_judge_llm_model", "label": "Judge 模型（空=复用 LLM）", "type": "text"},
            {"key": "eval_judge_llm_provider", "label": "Judge 提供商", "type": "text"},
            {"key": "eval_judge_llm_api_key", "label": "Judge API Key", "type": "secret"},
        ],
    },
]
